/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oops.project;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class Send_Money extends javax.swing.JFrame {

    /**
     * Creates new form Send_Money
     */
    Wallet o;
    public Send_Money(Wallet obj) {
        this.setUndecorated(true);
        initComponents();
        o = obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        amt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 80, 40));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Recipient User Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 230, -1));

        jTextField1.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 190, 30));

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jButton2.setText("Send Now");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 130, 40));

        amt.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        getContentPane().add(amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Amount");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 10, 110));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 142, 450, 10));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Send Money");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 230, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oops/project/use 2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        o.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:     
        try
        {
            if(jTextField1.getText().equals(o.o.userId))
            {
                JOptionPane.showMessageDialog(null, "You cannot transfer money to your own account", "Money not sent", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/customers", "root", "prakhar@18");

                double v = 0;
                int check = 0;
                int status = 0;
                String ss = "select * from customer_info where uid = '" + jTextField1.getText() + "'";
                PreparedStatement pst = conn.prepareStatement(ss);
                ResultSet r = pst.executeQuery();
                while(r.next())
                {
                    check = 1;
                    v = r.getDouble("bal");
                }
                ss = "select * from customer_info where uid = '" + o.o.userId + "'";
                pst = conn.prepareStatement(ss);
                r = pst.executeQuery();
                while(r.next())
                {
                    status = Integer.parseInt(r.getString("status"));
                }
                if(status == 1)
                {
                    JOptionPane.showMessageDialog(null, "You cannot send money while you are in a ride", "Money not sent", JOptionPane.ERROR_MESSAGE);
                }
                else if(check == 1)
                {
                    double val = 0.0;
            
                    String sq = "select bal from customer_info where uid = '" + o.o.userId + "'";
                    PreparedStatement pstm = conn.prepareStatement(sq);
                    ResultSet rs = pstm.executeQuery();
                    while(rs.next())
                    {
                        val = rs.getDouble("bal");
                    }
                    double d = Double.parseDouble(amt.getText());
                    d = Double.parseDouble(String.format("%.2f", d));
                    double updatedBal = val - d;
                    updatedBal = Double.parseDouble(String.format("%.2f", updatedBal));

                    if(d <= 0)
                    {
                        JOptionPane.showMessageDialog(null, "Invalid amount entered", "Money not sent", JOptionPane.ERROR_MESSAGE);
                    }
                    else if(updatedBal < 0)
                    {
                        JOptionPane.showMessageDialog(null, "Your balance is insufficient", "Money not sent", JOptionPane.ERROR_MESSAGE);
                    }
                    else
                    {
                        double upd = v + d;
                        String sqq = "update customer_info set bal = " + upd + " where uid = '" + jTextField1.getText() + "'";

                        PreparedStatement ps = conn.prepareStatement(sqq);
                        ps.executeUpdate();

                        String sss = "select * from customer_info where uid = '" + jTextField1.getText() + "'";
                        String wallethistor = "";
                        PreparedStatement pss = conn.prepareStatement(sss);            
                        ResultSet rrs = pss.executeQuery();
                        while(rrs.next())
                        {
                            wallethistor = rrs.getString("wallethistory");
                        }
                        String temp = Double.toString(d);
                        if(wallethistor.charAt(0) == '0')
                        {
                            wallethistor = "~" + o.o.userId + ": Rs. " + temp;
                        }
                        else
                        {
                            wallethistor = "~" + o.o.userId + ": Rs. " + temp + wallethistor;
                        }

                        String sqlll = "update customer_info set wallethistory = '" + wallethistor + "' where uid = '" + jTextField1.getText() + "'";

                        PreparedStatement pstmttt = conn.prepareStatement(sqlll);
                        pstmttt.executeUpdate();





                        String sql = "update customer_info set bal = " + updatedBal + " where uid = '" + o.o.userId + "'";

                        PreparedStatement pstmt = conn.prepareStatement(sql);
                        pstmt.executeUpdate();

                        String sqll = "select * from customer_info where uid = '" + o.o.userId + "'";
                        String wallethistory = "";
                        PreparedStatement pstmtt = conn.prepareStatement(sqll);            
                        ResultSet rss = pstmtt.executeQuery();
                        while(rss.next())
                        {
                            wallethistory = rss.getString("wallethistory");
                        }
                        temp = Double.toString(d);
                        if(wallethistory.charAt(0) == '0')
                        {
                            wallethistory = "!" + temp;
                        }
                        else
                        {
                            wallethistory = "!" + jTextField1.getText() + ": Rs. " + temp + wallethistory;
                        }

                        sqlll = "update customer_info set wallethistory = '" + wallethistory + "' where uid = '" + o.o.userId + "'";

                        pstmttt = conn.prepareStatement(sqlll);
                        pstmttt.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Rs. " + d + " sent to " + jTextField1.getText() + ". Please Refresh to view the New Balance");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "This user ID does not exist", "Money not sent", JOptionPane.ERROR_MESSAGE);
                }
                conn.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Invalid amount entered", "Money not sent", JOptionPane.ERROR_MESSAGE);
        }
            
            
            
            
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Send_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Send_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Send_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Send_Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Send_Money().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
