/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oops.project;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.regex.*;

/**
 *
 * @author vinay
 */
public class Sign_Up extends javax.swing.JFrame {

    /**
     * Creates new form Sign_Up
     */
    public Sign_Up() {
        this.setUndecorated(true);
//        this.setLocationRelativeTo(null);
//        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        uid = new javax.swing.JTextField();
        phno = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        cpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        errorfn = new javax.swing.JLabel();
        erroremail = new javax.swing.JLabel();
        errorphno = new javax.swing.JLabel();
        erroruid = new javax.swing.JLabel();
        errorln = new javax.swing.JLabel();
        errorcpass = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TAXI");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Sign Up");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 140, 50));

        fn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnFocusLost(evt);
            }
        });
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        fn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnKeyReleased(evt);
            }
        });
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 170, 30));

        ln.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnFocusLost(evt);
            }
        });
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        ln.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lnKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnKeyReleased(evt);
            }
        });
        jPanel1.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 170, 30));

        uid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                uidFocusLost(evt);
            }
        });
        uid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uidKeyReleased(evt);
            }
        });
        jPanel1.add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 170, 30));

        phno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phnoFocusLost(evt);
            }
        });
        phno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnoActionPerformed(evt);
            }
        });
        phno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phnoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phnoKeyReleased(evt);
            }
        });
        jPanel1.add(phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 170, 30));

        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 170, 30));

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passKeyReleased(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 170, 30));

        cpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpassActionPerformed(evt);
            }
        });
        cpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpassKeyReleased(evt);
            }
        });
        jPanel1.add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Email ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("an Uppercase Letter, a digit and a special symbol)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Confirm");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 80, 30));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("First Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("User ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Phone No.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 3, 20)); // NOI18N
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 130, 40));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Password");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 110, 40));

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 30));

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 0));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Show Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 140, -1));

        errorfn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 17)); // NOI18N
        errorfn.setForeground(new java.awt.Color(255, 0, 0));
        errorfn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                errorfnKeyPressed(evt);
            }
        });
        jPanel1.add(errorfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 380, 30));

        erroremail.setFont(new java.awt.Font("Tempus Sans ITC", 1, 17)); // NOI18N
        erroremail.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(erroremail, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 380, 30));

        errorphno.setFont(new java.awt.Font("Tempus Sans ITC", 1, 17)); // NOI18N
        errorphno.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errorphno, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 380, 30));

        erroruid.setFont(new java.awt.Font("Tempus Sans ITC", 1, 17)); // NOI18N
        erroruid.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(erroruid, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 380, 30));

        errorln.setFont(new java.awt.Font("Tempus Sans ITC", 1, 17)); // NOI18N
        errorln.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errorln, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 380, 30));

        errorcpass.setFont(new java.awt.Font("Tempus Sans ITC", 1, 17)); // NOI18N
        errorcpass.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errorcpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 380, 30));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Password");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("(atleast 4 characters, a lowercase letter,");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oops/project/use 2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1001, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void phnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_phnoActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void cpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(fn.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill in your First Name", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(ln.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill in your Last Name", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(uid.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "User ID cannot be empty. Please set your user ID", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(phno.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please provide your Phone Number", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(email.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please provide your email ID", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(new String(pass.getPassword()).trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Password field is empty. Please set a password for your profile", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(!new String(pass.getPassword()).equals(new String(cpass.getPassword())))
        {
            JOptionPane.showMessageDialog(null, "Passwords do not match", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(fn.getText().length() > 100)
        {
            JOptionPane.showMessageDialog(null, "Only 100 characters allowed in first name", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(ln.getText().length() > 100)
        {
            JOptionPane.showMessageDialog(null, "Only 100 characters allowed in last name", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(uid.getText().length() > 100)
        {
            JOptionPane.showMessageDialog(null, "Only 100 characters allowed in User ID", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(email.getText().length() > 300)
        {
            JOptionPane.showMessageDialog(null, "Only 300 characters allowed in email", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String phone = phno.getText();
            String pattern = "^[1-9][0-9]{9}$";
            Pattern p = Pattern.compile(pattern);
            Matcher m = p.matcher(phone);
            
            String password = new String(pass.getPassword());
            String pattern2 = "((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[`~!@#$%^&*\\(\\)\\?<>,./;:+{}\\[\\]\\'=|_-]).{4,50})";
            Pattern p2 = Pattern.compile(pattern2);
            Matcher m2 = p2.matcher(password);
            
            String mail = email.getText();
            String pattern3 = "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?!-)(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$";
            Pattern p3 = Pattern.compile(pattern3);
            Matcher m3 = p3.matcher(mail);

            if(!m.matches())
            {
                JOptionPane.showMessageDialog(null, "Invalid Mobile Number", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(!m3.matches())
            {
                JOptionPane.showMessageDialog(null, "Invalid Email ID entered", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else if(!m2.matches())
            {
                JOptionPane.showMessageDialog(null, "Password must have atleast 4 and atmost 50 characters, a lowercase letter, an Uppercase Letter, a digit and a special symbol", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                try
                {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/customers", "root", "prakhar@18");
                    String sql = "insert into customer_info values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
                    PreparedStatement pstmt = conn.prepareStatement(sql);
            
                    pstmt.setString(1, fn.getText());
                    pstmt.setString(2, ln.getText());
                    pstmt.setString(3, uid.getText());
                    pstmt.setString(4, phno.getText());
                    pstmt.setString(5, email.getText());
                    pstmt.setString(6, new String(pass.getPassword()));
                    pstmt.setDouble(7, 0);
                    pstmt.setString(8, "0");
                    pstmt.setString(9, "-1");
                    pstmt.setString(10, "0");
                    pstmt.setString(11, "0");
                    pstmt.setString(12, "0");
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Account created. You can sign in now and enjoy your ride!");
                    conn.close();
                    this.setVisible(false);
                    new Sign_In().setVisible(true);
                }
                catch(Exception e)
                {
                    // "This User ID is not available. Please type another user ID"
                    JOptionPane.showMessageDialog(null, "This User ID is not available. Please type another user ID", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Sign_In().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected())
        {
            pass.setEchoChar((char)0); //password = JPasswordField
            cpass.setEchoChar((char)0);
        }
        else
        {
            pass.setEchoChar('*');
            cpass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void phnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phnoKeyPressed
        // TODO add your handling code here:
        char[] ar = {'`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '[', ']', '{', '}', '|', ';', ':', '<', ',', '>', '.', '/', '?', '"', '\\', '\'', ' '};
        char c = evt.getKeyChar();
        int k = evt.getKeyCode();
        if(Character.isDigit(c) || c == '\b' || k == 37 || k == 38 || k == 39 || k == 40 || k == 127 || k == 36 || k == 35)
        {
            errorphno.setText("");
        }
        else
        {
            if(Character.isAlphabetic(c))
            {
                phno.setEditable(false);
                errorphno.setText("Please enter numbers only");
            }
            else
            {
                for(int i = 0; i < 43; i++)
                {
                    if(ar[i] == c)
                    {
                        phno.setEditable(false);
                        errorphno.setText("Please enter numbers only");
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_phnoKeyPressed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void fnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyPressed
        // TODO add your handling code here:
        char[] ar = {'`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '[', ']', '{', '}', '|', ';', ':', '<', ',', '>', '.', '/', '?', '"', '\\', '\'', ' '};
        char c = evt.getKeyChar();
        int k = evt.getKeyCode();
        if(Character.isAlphabetic(c) || c == '\b' || k == 37 || k == 38 || k == 39 || k == 40 || k == 127 || k == 36 || k == 35)
        {
            errorfn.setText("");
        }
        else
        {
            for(int i = 0; i < 43; i++)
            {
                if(ar[i] == c)
                {
                    fn.setEditable(false);
                    errorfn.setText("Only alphabets allowed");
                    break;
                }
            }
        }
        
    }//GEN-LAST:event_fnKeyPressed

    private void lnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnKeyPressed
        // TODO add your handling code here:  
        char[] ar = {'`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '[', ']', '{', '}', '|', ';', ':', '<', ',', '>', '.', '/', '?', '"', '\\', '\'', ' '};
        char c = evt.getKeyChar();
        int k = evt.getKeyCode();
        if(Character.isAlphabetic(c) || c == '\b' || k == 37 || k == 38 || k == 39 || k == 40 || k == 127 || k == 36 || k == 35)
        {
            errorln.setText("");
        }
        else
        {
            for(int i = 0; i < 43; i++)
            {
                if(ar[i] == c)
                {
                    ln.setEditable(false);
                    errorln.setText("Only alphabets allowed");
                    break;
                }
            }
        }
    }//GEN-LAST:event_lnKeyPressed

    private void uidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uidKeyPressed
        // TODO add your handling code here:
        char[] ar = {'`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '[', ']', '{', '}', '|', ';', ':', '<', ',', '>', '.', '/', '?', '"', '\\', '\'', ' '};
        char c = evt.getKeyChar();
        int k = evt.getKeyCode();
        if(Character.isAlphabetic(c) || Character.isDigit(c) || c == '.' || c == '_' || c == '\b' || k == 37 || k == 38 || k == 39 || k == 40 || k == 127 || k == 36 || k == 35)
        {
            erroruid.setText("");
        }
        else
        {
            for(int i = 0; i < 43; i++)
            {
                if(ar[i] == c)
                {
                    uid.setEditable(false);
                    erroruid.setText("You can enter alphabets, digits, . or _ only");
                    break;
                }
            }
        }
    }//GEN-LAST:event_uidKeyPressed

    private void cpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpassKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpassKeyPressed

    private void cpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpassKeyReleased
        // TODO add your handling code here:
        String s1 = new String(pass.getPassword());
        String s2 = new String(cpass.getPassword());
        if(!s1.equals(s2))
        {
            errorcpass.setText("Passwords do no match");
        }
        else
        {
            errorcpass.setText("");
        }
    }//GEN-LAST:event_cpassKeyReleased

    private void errorfnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_errorfnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorfnKeyPressed

    private void passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyReleased
        // TODO add your handling code here:
        String s1 = new String(pass.getPassword());
        String s2 = new String(cpass.getPassword());
        if(!s1.equals(s2))
        {
            errorcpass.setText("Passwords do no match");
        }
        else
        {
            errorcpass.setText("");
        }
    }//GEN-LAST:event_passKeyReleased

    private void fnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnKeyReleased
        // TODO add your handling code here:
        fn.setEditable(true);
    }//GEN-LAST:event_fnKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
//        ln.setEditable(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void lnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnKeyReleased
        // TODO add your handling code here:
        ln.setEditable(true);
    }//GEN-LAST:event_lnKeyReleased

    private void lnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnFocusLost
        // TODO add your handling code here:
        errorln.setText("");
        if(ln.getText().trim().isEmpty())
        {
            errorln.setText("Last Name cannot be empty");
        }
    }//GEN-LAST:event_lnFocusLost

    private void fnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnFocusLost
        // TODO add your handling code here:
        errorfn.setText("");
        if(fn.getText().trim().isEmpty())
        {
            errorfn.setText("First Name cannot be empty");
        }
    }//GEN-LAST:event_fnFocusLost

    private void uidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uidFocusLost
        // TODO add your handling code here:
        erroruid.setText("");
        if(uid.getText().trim().isEmpty())
        {
            erroruid.setText("User ID cannot be empty");
        }
    }//GEN-LAST:event_uidFocusLost

    private void phnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phnoFocusLost
        // TODO add your handling code here:
        errorphno.setText("");
        if(phno.getText().trim().isEmpty())
        {
            errorphno.setText("Phone Number cannot be empty");
        }
    }//GEN-LAST:event_phnoFocusLost

    private void uidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uidKeyReleased
        // TODO add your handling code here:
        uid.setEditable(true);
    }//GEN-LAST:event_uidKeyReleased

    private void phnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phnoKeyReleased
        // TODO add your handling code here:
        phno.setEditable(true);
    }//GEN-LAST:event_phnoKeyReleased

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cpass;
    private javax.swing.JTextField email;
    private javax.swing.JLabel errorcpass;
    private javax.swing.JLabel erroremail;
    private javax.swing.JLabel errorfn;
    private javax.swing.JLabel errorln;
    private javax.swing.JLabel errorphno;
    private javax.swing.JLabel erroruid;
    private javax.swing.JTextField fn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ln;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField phno;
    private javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
